# Generated by Django 2.2 on 2019-05-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outfits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothingItem',
        ),
    ]
