# Generated by Django 2.2 on 2019-06-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Outfits', '0003_clothingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='upper', max_length=20)),
                ('name', models.CharField(default='shirt', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='clothes_pics')),
            ],
        ),
        migrations.CreateModel(
            name='StyleOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(to='Outfits.PossibleItem')),
            ],
        ),
        migrations.CreateModel(
            name='BadOutfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='Outfits.ClothingItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
