# Generated by Django 2.2 on 2019-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outfits', '0004_badoutfit_possibleitem_styleone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(to='Outfits.PossibleItem')),
            ],
        ),
        migrations.CreateModel(
            name='StyleThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(to='Outfits.PossibleItem')),
            ],
        ),
    ]
